backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Galeria"
    folder: "gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł zdjęcia", name: "title", widget: "string" }
      - { label: "Obraz", name: "image", widget: "image" }
